import wmi
#
# def Memory_Info():
#     c = wmi.WMI()
#     memory_list=[]
#     c.
#     for physical_memory in c.Win32_PhysicalMemory():
#

c = wmi.WMI()

for Desktop in c.Win32_Desktop():
    print(Desktop)
    # for Desktop_item in Desktop:
    #     print(Desktop_item)

# for cls in c.classes:
#     print(cls)


# CIM_PhysicalCapacity
# CIM_ProductFRU
# CIM_USBController
# Win32_TerminalService
# Win32_ShadowDiffVolumeSupport
# Win32_MemoryDevice
# Win32_PerfFormattedData_Counters_ThermalZoneInformation
# Win32_PerfRawData_Counters_PacketDirectReceiveFilters
# Win32_PrinterConfiguration
# Win32_PerfFormattedData_DdmCounterProvider_RAS
# Win32_ShadowCopy
# CIM_FRUPhysicalElements
# CIM_SlotInSlot
# Win32_PerfRawData_Counters_TeredoServer
# Win32_PerfFormattedData_WinNatCounters_WinNATUDP
# __SystemSecurity
# CIM_LogicalFile
# CIM_ChassisInRack
# CIM_AdjacentSlots
# Win32_PerfRawData_PerfOS_Processor
# Win32_ShadowStorage
# Win32_PerfRawData_PeerNameResolutionProtocolPerf_PeerNameResolutionProtocol
# Win32_DiskPartition
# CIM_LogicalDiskBasedOnPartition
# CIM_SoftwareFeature
# Msft_WmiProvider_CreateInstanceEnumAsyncEvent_Pre
# CIM_PCIController
# Win32_ODBCSourceAttribute
# CIM_DiskPartition
# Win32_PerfFormattedData_Counters_SMBServerShares
# CIM_AggregateRedundancyComponent
# Win32_PerfFormattedData_Counters_IPsecIKEv2IPv4
# Win32_PerfFormattedData_PerfProc_Thread
# Win32_ServerConnection
# Win32_PnPDevice
# CIM_PhysicalFrame
# Win32_Registry
# Win32_PerfFormattedData_Counters_HyperVVirtualMachineBus
# MSFT_NetServiceStartTypeChanged
# Win32_PrinterDriverDll
# CIM_AllocatedResource
# Win32_PerfFormattedData_Counters_PacketDirectECUtilization
# Win32_IDEController
# CIM_AssociatedBattery
# CIM_PhysicalExtent
# CIM_ErrorCountersForDevice
# Win32_SelfRegModuleAction
# Win32_ImplementedCategory
# Win32_BaseService
# Win32_ControllerHasHub
# Win32_PerfFormattedData_Counters_SMBClientShares
# Win32_RoamingProfileMachineConfiguration
# CIM_ApplicationSystem
# Win32_SecuritySettingAuditing
# Win32_PerfRawData_FaxService_FaxService
# Win32_PerfFormattedData_PerfNet_ServerWorkQueues
# Win32_NTLogEvent
# Win32_ProtocolBinding
# Win32_ODBCDataSourceAttribute
# CIM_Printer
# CIM_ClusterServiceAccessBySAP
# MSFT_WmiThreadPoolEvent
# CIM_PackageAlarm
# __TimerEvent
# Win32_ProgIDSpecification
# Win32_PnPDevicePropertyBooleanArray
# CIM_ResidesOnExtent
# Win32_PnPDevicePropertySint8
# Win32_LogicalProgramGroupItem
# Win32_PerfFormattedData_Counters_RemoteFXNetwork
# Win32_Reliability
# Win32_MemoryDeviceArray
# Win32_PerfRawData_Counters_IPsecAuthIPIPv4
# Win32_PerfRawData_Counters_NetworkQoSPolicy
# Win32_PerfRawData_AuthorizationManager_AuthorizationManagerApplications
# MSFT_SCMEventLogEvent
# Win32_OfflineFilesFileSysInfo
# Win32_PerfRawData_McePerfCtr_ClassificationEngineRulePackageCache
# Msft_WmiProvider_PutInstanceAsyncEvent_Post
# Win32_PerfFormattedData_Counters_ProcessorInformation
# Win32_PerfFormattedData_Counters_WFPClassify
# CIM_PhysicalElement
# CIM_BinarySensor
# Win32_PerfRawData_PerfOS_PagingFile
# Win32_InstalledStoreProgram
# __PropertyProviderRegistration
# Win32_SoftwareFeatureParent
# CIM_TapeDrive
# Win32_DCOMApplication
# MSFT_NetFirstLogonFailed
# Win32_PerfFormattedData_Counters_SMBServer
# Win32_PerfFormattedData_HvStats_HyperVHypervisorRootVirtualProcessor
# CIM_Card
# Win32_PnPDevicePropertyReal64Array
# CIM_RealizesDiskPartition
# Win32_IP4RouteTableEvent
# CIM_StorageExtent
# Win32_PerfFormattedData_Tcpip_IPv6
# Win32_ShadowBy
# Win32_FontInfoAction
# Win32_PnPEntity
# CIM_FromDirectoryAction
# CIM_VideoController
# Win32_NTDomain
# CIM_VideoBIOSElement
# Win32_ComputerSystem
# Win32_MethodParameterClass
# Win32_OfflineFilesConnectionInfo
# CIM_AggregatePExtent
# CIM_NumericSensor
# Win32_VolumeChangeEvent
# Win32_PerfFormattedData_MicrosoftWindowsBitLockerDriverCountersProvider_BitLocker
# Win32_PnPDevicePropertySecurityDescriptor
# Win32_PerfRawData_MSDTC_DistributedTransactionCoordinator
# Win32_PerfRawData_WinNatCounters_WinNATTCP
# Win32_ShareToDirectory
# Win32_PerfFormattedData_Counters_ReFS
# Win32_PerfRawData_Counters_IPsecIKEv1IPv4
# CIM_Statistics
# Win32_PnPDevicePropertyUint32
# __ClassModificationEvent
# CIM_PExtentRedundancyComponent
# Win32_PnPDevicePropertySecurityDescriptorArray
# Win32_GroupUser
# Win32_LogicalFileSecuritySetting
# CIM_PhysicalMemory
# Win32_DfsNode
# CIM_SystemDevice
# Win32_PerfRawData_Tcpip_NetworkInterface
# CIM_ManagedSystemElement
# CIM_OperatingSystem
# CIM_ElementsLinked
# Win32_Desktop
# Win32_CheckCheck
# RegistryKeyChangeEvent
# Win32_DeviceSettings
# Win32_PerfFormattedData_NETCLRNetworking_NETCLRNetworking
# CIM_MediaPresent
# CIM_ClassModification
# Win32_PerfRawData_Counters_HyperVVirtualMachineBusPipes
# Win32_PerfFormattedData_UGTHRSVC_SearchGatherer
# Win32_PerfFormattedData_SMSvcHost4000_SMSvcHost4000
# Win32_COMClass
# Win32_CIMLogicalDeviceCIMDataFile
# Win32_DCOMApplicationAccessAllowedSetting
# Win32_MountPoint
# Msft_WmiProvider_PutClassAsyncEvent_Pre
# CIM_ClassDeletion
# Win32_Patch
# CIM_Product
# Win32_PerfFormattedData_FaxService_FaxService
# Win32_PerfFormattedData_PerfNet_Redirector
# Win32_PerfFormattedData_PerfOS_Cache
# Win32_PrintJob
# Win32_PerfRawData_SMSvcHost4000_SMSvcHost4000
# CIM_PCVideoController
# MSFT_WmiFilterEvent
# CIM_ProductPhysicalElements
# CIM_HostedAccessPoint
# Win32_ThreadStopTrace
# Win32_PerfFormattedData_Counters_DNS64Global
# __IndicationRelated
# Win32_PerfRawData_Counters_HTTPServiceRequestQueues
# Win32_PerfRawData_Counters_HyperVVirtualMachineBus
# Win32_LogicalShareSecuritySetting
# CIM_Chassis
# Win32_COMApplicationClasses
# MSFT_NetDependOnLaterService
# Win32_SerialPortConfiguration
# Win32_PerfRawData_Counters_SMBServerSessions
# Win32_PerfRawData_ServiceModelService3000_ServiceModelService3000
# Win32_PerfRawData_Counters_StorageSpacesTier
# Win32_PnPDevicePropertyUint16Array
# CIM_LogicalDiskBasedOnVolumeSet
# Win32_CacheMemory
# Win32_EnvironmentSpecification
# Win32_PerfRawData_Counters_SynchronizationNuma
# Msft_WmiProvider_ExecQueryAsyncEvent_Post
# Win32_SecuritySettingOfObject
# Win32_PerfFormattedData_Counters_IPsecIKEv1IPv6
# __MethodProviderRegistration
# CIM_VersionCompatibilityCheck
# CIM_ClusteringService
# Win32_ODBCTranslatorSpecification
# __QOSFailureEvent
# Win32_PnPDevicePropertySint16Array
# CIM_AssociatedSensor
# Win32_PerfFormattedData_Counters_WFPv4
# CIM_DataFile
# Win32_PerfFormattedData_Counters_IPHTTPSSession
# Win32_PerfRawData_Tcpip_NBTConnection
# Win32_PerfRawData_Counters_EventTracingforWindows
# Win32_PerfRawData_MicrosoftWindowsBitLockerDriverCountersProvider_BitLocker
# CIM_MultiStateSensor
# Win32_PerfRawData_WSearchIdxPi_SearchIndexer
# Win32_OperatingSystemAutochkSetting
# Win32_Directory
# Win32_PerfFormattedData_Tcpip_NetworkInterface
# Win32_PerfRawData_AFDCounters_MicrosoftWinsockBSP
# Win32_PerfFormattedData_NETDataProviderforOracle_NETDataProviderforOracle
# Win32_ClassicCOMApplicationClasses
# Win32_PerfFormattedData_Counters_TeredoServer
# Win32_PerfFormattedData_MSDTCBridge3000_MSDTCBridge3000
# CIM_InstCreation
# CIM_DeviceSAPImplementation
# CIM_SerialInterface
# Win32_PerfRawData_PerfDisk_LogicalDisk
# __NamespaceCreationEvent
# Win32_DisplayControllerConfiguration
# Win32_ClassicCOMClass
# CIM_Directory
# __SystemEvent
# CIM_BIOSElement
# Win32_SoftwareFeatureCheck
# Win32_PerfRawData_Counters_WSManQuotaStatistics
# CIM_StatisticalInformation
# Win32_PerfRawData_GPUPerformanceCounters_GPUEngine
# Win32_Printer
# MSFT_NCProvNewQuery
# Win32_PnPSignedDriver
# Win32_PerfRawData_Counters_RemoteFXNetwork
# Win32_MIMEInfoAction
# Win32_PerfFormattedData_ServiceModelOperation3000_ServiceModelOperation3000
# MSFT_NetServiceStartFailed
# CIM_FRUIncludesProduct
# CIM_BIOSFeature
# MSFT_NetCircularDependencyAuto
# Win32_COMSetting
# Win32_ProgramGroupOrItem
# Win32_PerfRawData_Tcpip_IPv4
# CIM_DirectorySpecification
# Win32_ShadowOn
# MSFT_SCMEvent
# Win32_PerfRawData_Counters_XHCITransferRing
# __MethodInvocationEvent
# CIM_PhysicalMedia
# Win32_ParallelPort
# MSFT_WmiFilterActivated
# MSFT_NetReadfileTimeout
# Win32_SecuritySetting
# Win32_LogicalProgramGroupItemDataFile
# Win32_PerfRawData_Counters_ReFS
# Win32_PerfFormattedData_rdyboost_ReadyBoostCache
# MSFT_WmiConsumerProviderSinkLoaded
# Win32_SystemResources
# CIM_ServiceAccessBySAP
# __EventFilter
# Win32_FileSpecification
# CIM_SwapSpaceCheck
# CIM_VoltageSensor
# CIM_MagnetoOpticalDrive
# Win32_SessionResource
# Win32_OfflineFilesDiskSpaceLimit
# Win32_SecuritySettingGroup
# Win32_PerfFormattedData_Counters_NetworkQoSPolicy
# Win32_PerfRawData_UGTHRSVC_SearchGatherer
# Win32_PerfFormattedData_Counters_HTTPServiceRequestQueues
# Win32_PerfFormattedData_HvStats_HyperVHypervisorLogicalProcessor
# Msft_WmiProvider_ExecMethodAsyncEvent_Post
# CIM_ConnectedTo
# CIM_AssociatedMemory
# Win32_ConnectionShare
# Win32_PerfRawData_Counters_StorageSpacesWriteCache
# Win32_PrinterSetting
# Win32_HeatPipe
# Win32_PhysicalMedia
# Win32_SoftwareFeatureAction
# Win32_SoftwareElementCondition
# CIM_DirectorySpecificationFile
# MSFT_NetCircularDependencyDemand
# Win32_PerfFormattedData_PeerNameResolutionProtocolPerf_PeerNameResolutionProtocol
# Win32_PerfRawData_Counters_WFPReauthentication
# CIM_DeviceSoftware
# Msft_WmiProvider_InitializationOperationEvent
# Win32_PerfFormattedData_Counters_WFP
# Win32_PerfRawData_Tcpip_UDPv4
# Win32_PerfRawData_Counters_ProcessorInformation
# Win32_PerfRawData_DdmCounterProvider_RAS
# __InstanceProviderRegistration
# Win32_LogicalFileAccess
# Win32_SoftwareElementAction
# CIM_RealizesAggregatePExtent
# CIM_CurrentSensor
# Win32_SystemBIOS
# CIM_Error
# Win32_WMISetting
# Win32_SerialPortSetting
# Win32_PerfRawData_Counters_Netlogon
# MSFT_WmiThreadPoolThreadDeleted
# Win32_PageFileSetting
# MSFT_WmiConsumerProviderEvent
# Win32_CollectionStatistics
# CIM_Controller
# Win32_MotherboardDevice
# CIM_ClusteringSAP
# Msft_WmiProvider_PutInstanceAsyncEvent_Pre
# Msft_WmiProvider_UnLoadOperationEvent
# Win32_ManagedSystemElementResource
# Win32_PhysicalMemory
# Win32_PnPDevicePropertySint32Array
# Win32_SystemServices
# MSFT_NetBootSystemDriversFailed
# CIM_Indication
# Win32_ProductCheck
# CIM_PackagedComponent
# CIM_CacheMemory
# CIM_SoftwareElementActions
# Win32_PerfRawData_WinNatCounters_WinNATICMP
# __ProviderRegistration
# CIM_ConnectorOnPackage
# Win32_PerfRawData_Counters_SMBDirectConnection
# MSFT_NetServiceCrash
# Win32_PerfRawData_MicrosoftWindowsW32TimePerf_WindowsTimeService
# MSFT_ExtendedStatus
# __ConsumerFailureEvent
# CIM_VideoBIOSFeature
# Win32_Processor
# Win32_PrinterDriver
# CIM_DeviceFile
# Win32_PerfRawData_GPUPerformanceCounters_GPUAdapterMemory
# Win32_PerfFormattedData_WinNatCounters_WinNATICMP
# CIM_FileSpecification
# CIM_Configuration
# Win32_VideoConfiguration
# Win32_NamedJobObjectStatistics
# Win32_CDROMDrive
# Win32_PerfRawData_WinNatCounters_WinNAT
# Win32_PerfFormattedData_Counters_RemoteFXGraphics
# Win32_PerfFormattedData_PerfNet_Server
# Win32_BindImageAction
# Win32_PerfRawData_MSDTCBridge4000_MSDTCBridge4000
# Win32_PerfRawData_BITS_BITSNetUtilization
# __SecurityRelatedClass
# Win32_SubSession
# CIM_CollectedCollections
# CIM_PointingDevice
# Win32_PerfRawData_Counters_RDMAActivity
# MSFT_NetServiceStartFailedNone
# CIM_MemoryWithMedia
# Win32_PerfFormattedData_Counters_XHCITransferRing
# Msft_WmiProvider_AccessCheck_Post
# Win32_ServiceControl
# CIM_SoftwareFeatureServiceImplementation
# MSFT_NetDependOnLaterGroup
# Win32_NTLogEventComputer
# Win32_PerfFormattedData_Counters_IPsecConnections
# Win32_PerfFormattedData_PerfNet_Browser
# Msft_WmiProvider_OperationEvent_Pre
# CIM_Setting
# CIM_FRU
# Win32_PerfRawData_NETDataProviderforSqlServer_NETDataProviderforSqlServer
# CIM_PCMCIAController
# Win32_PerfFormattedData_DistributedRoutingTablePerf_DistributedRoutingTable
# Msft_WmiProvider_GetObjectAsyncEvent_Post
# Win32_SystemTrace
# Win32_CreateFolderAction
# Win32_ShortcutSAP
# CIM_JobDestinationJobs
# Win32_StartupCommand
# CIM_Action
# CIM_ActionSequence
# Win32_PerfRawData_PerfDisk_PhysicalDisk
# Win32_SecuritySettingOfLogicalShare
# RegistryEvent
# Win32_MappedLogicalDisk
# Win32_ApplicationService
# Win32_1394ControllerDevice
# Win32_DCOMApplicationLaunchAllowedSetting
# MSFT_WmiConsumerProviderLoaded
# CIM_StorageVolume
# Win32_PageFile
# CIM_ToDirectoryAction
# Win32_PerfFormattedData_NETFramework_NETCLRLoading
# Win32_PerfFormattedData_PerfOS_System
# CIM_CollectionOfSensors
# CIM_RemoveDirectoryAction
# CIM_ProcessExecutable
# CIM_ProductSoftwareFeatures
# Win32_RoamingProfileUserConfiguration
# Win32_SIDandAttributes
# Win32_PerfRawData_ESENT_DatabaseInstances
# Win32_PerfRawData_NETMemoryCache40_NETMemoryCache40
# Win32_USBControllerDevice
# Win32_SystemPartitions
# Win32_PerfRawData_TCPIPCounters_TCPIPPerformanceDiagnostics
# Win32_PerfRawData_HvStats_HyperVHypervisorRootPartition
# Win32_ODBCDriverAttribute
# Win32_MoveFileAction
# Win32_PnPDevicePropertyReal32Array
# __EventProviderRegistration
# Win32_OperatingSystemQFE
# Win32_PerfRawData_Counters_DNS64Global
# CIM_BootSAP
# MSFT_NetTakeOwnership
# MSFT_WmiError
# CIM_SCSIInterface
# MSFT_NetServiceStartHung
# Win32_SystemNetworkConnections
# CIM_ApplicationSystemSoftwareFeature
# Win32_PnPDevicePropertyReal64
# Win32_PnPDevicePropertyUint64
# Win32_PnPDevicePropertySint16
# Win32_LoadOrderGroupServiceDependencies
# Win32_PerfFormattedData_Counters_HyperVDynamicMemoryIntegrationService
# CIM_FlatPanel
# Win32_PerfRawData_Counters_RemoteFXGraphics
# Win32_PerfRawData_Counters_IPsecIKEv2IPv4
# Win32_PerfFormattedData_WSearchIdxPi_SearchIndexer
# __PARAMETERS
# Win32_SCSIController
# CIM_HostedBootSAP
# Win32_PerfFormattedData_Tcpip_NetworkAdapter
# SoftwareLicensingService
# Win32_POTSModemToSerialPort
# Win32_PerfFormattedData_WindowsWorkflowFoundation3000_WindowsWorkflowFoundation
# Win32_PerfRawData_MSDTCBridge3000_MSDTCBridge3000
# Win32_PerfFormattedData_PerfOS_NUMANodeMemory
# Win32_ClassicCOMClassSettings
# __NotifyStatus
# __NamespaceModificationEvent
# CIM_CardOnCard
# CIM_PackageInSlot
# CIM_Tachometer
# Win32_PerfFormattedData_WnvCounters_NetworkVirtualization
# CIM_StorageRedundancyGroup
# Win32_PerfRawData_Counters_SMBServerShares
# Win32_PerfFormattedData_TapiSrv_Telephony
# Win32_VideoSettings
# Win32_DMAChannel
# Win32_PerfFormattedData_Counters_SMBDirectConnection
# Win32_PerfRawData_OfflineFiles_OfflineFiles
# Win32_PerfRawData_RemoteAccess_RASPort
# CIM_MemoryCheck
# CIM_Chip
# Win32_ShadowProvider
# __EventConsumerProviderRegistration
# Win32_NamedJobObjectSecLimit
# CIM_LinkHasConnector
# Win32_ShadowFor
# Win32_SoftwareFeature
# Win32_VideoController
# Win32_PerfFormattedData_TCPIPCounters_TCPIPPerformanceDiagnosticsPerCPU
# Win32_QuotaSetting
# ScriptingStandardConsumerSetting
# Win32_PerfFormattedData_HvStats_HyperVHypervisorRootPartition
# Win32_ThreadTrace
# CIM_Scanner
# CIM_InstModification
# Win32_PerfFormattedData_Counters_AppVClientStreamedDataPercentage
# Win32_SystemLoadOrderGroups
# Win32_SCSIControllerDevice
# Win32_PerfRawData_ServiceModelEndpoint3000_ServiceModelEndpoint3000
# __SystemClass
# CIM_ControlledBy
# Win32_LocalTime
# Win32_ComClassAutoEmulator
# MSFT_WmiProviderEvent
# Win32_PerfFormattedData_PerfOS_Memory
# CIM_DirectoryContainsFile
# Win32_PerfFormattedData_PerfOS_Objects
# Win32_ReliabilityRecords
# Win32_WinSAT
# Win32_SystemOperatingSystem
# Win32_ModuleTrace
# Msft_WmiProvider_NewQuery_Post
# Msft_WmiProvider_CancelQuery_Pre
# Win32_ServiceSpecification
# Win32_POTSModem
# Win32_PnPDevicePropertyUint32Array
# Win32_SettingCheck
# CIM_Realizes
# Win32_PerfRawData_Counters_IPsecConnections
# Win32_SecurityDescriptor
# Win32_PerfRawData_NETFramework_NETCLRLoading
# Win32_ComClassEmulator
# Win32_Refrigeration
# Win32_Perf
# Win32_AssociatedProcessorMemory
# MSFT_WmiConsumerProviderUnloaded
# Msft_WmiProvider_ExecMethodAsyncEvent_Pre
# MSFT_NetServiceStatusSuccess
# Win32_ProcessTrace
# Win32_DeviceChangeEvent
# Win32_SID
# CIM_PhysicalComponent
# Win32_ReliabilityStabilityMetrics
# Win32_TokenPrivileges
# Win32_LogonSessionMappedDisk
# CIM_VolatileStorage
# Win32_PerfFormattedData_ESENT_DatabaseInstances
# CIM_DiskSpaceCheck
# CIM_CollectedMSEs
# CIM_Rack
# Win32_SecuritySettingAccess
# Win32_PerfRawData_McePerfCtr_ClassificationEngineContentAnalysisSession
# __AggregateEvent
# MSFT_NetTransactInvalid
# RegistryTreeChangeEvent
# MSFT_NetBadAccount
# Win32_Battery
# Win32_ShadowContext
# CIM_SpareGroup
# CIM_ProductSupport
# CIM_RedundancyGroup
# Msft_WmiProvider_ComServerLoadOperationFailureEvent
# CIM_Location
# MSFT_NetServiceDifferentPIDConnected
# Win32_NamedJobObjectLimitSetting
# Win32_PerfRawData_SMSvcHost3000_SMSvcHost3000
# Win32_NTLogEventLog
# Win32_PerfRawData_Counters_PacketDirectECUtilization
# CIM_Display
# CIM_ComputerSystemIRQ
# Win32_DiskDrivePhysicalMedia
# Win32_PerfFormattedData_AFDCounters_MicrosoftWinsockBSP
# Win32_PageFileUsage
# Win32_SessionConnection
# Win32_PerfFormattedData_GPUPerformanceCounters_GPUAdapterMemory
# Win32_PerfFormattedData_ServiceModelEndpoint3000_ServiceModelEndpoint3000
# CIM_PotsModem
# Win32_NetworkProtocol
# CIM_ToDirectorySpecification
# Win32_PerfFormattedData_Counters_HTTPService
# Win32_PerfFormattedData_Counters_PhysicalNetworkInterfaceCardActivity
# CIM_ActsAsSpare
# Win32_PerfRawData_PowerMeterCounter_EnergyMeter
# Win32_PerfRawData_Counters_HyperVDynamicMemoryIntegrationService
# MSFT_WmiConsumerProviderSinkUnloaded
# __EventDroppedEvent
# Win32_Volume
# Win32_PerfRawData_Tcpip_ICMPv6
# Win32_NamedJobObjectActgInfo
# Win32_PerfRawData_Counters_HTTPService
# Win32_UserAccount
# CIM_ServiceAccessPoint
# MSFT_NCProvCancelQuery
# Win32_DiskDriveToDiskPartition
# Win32_PerfFormattedData_Counters_Netlogon
# Win32_PerfFormattedData_NETCLRData_NETCLRData
# Win32_PerfFormattedData_GPUPerformanceCounters_GPUEngine
# Win32_OfflineFilesPinInfo
# Win32_PerfFormattedData_NETFramework_NETCLRMemory
# Win32_PerfRawData_PowerMeterCounter_PowerMeter
# __ACE
# Win32_PublishComponentAction
# CIM_Component
# Win32_PerfRawData_Counters_IPHTTPSGlobal
# Win32_DriverForDevice
# Win32_PerfRawData_Counters_HTTPServiceUrlGroups
# Win32_PerfRawData_PerfNet_Server
# Win32_PerfFormattedData_Tcpip_ICMP
# CIM_ParticipatesInSet
# CIM_SerialController
# CIM_OSProcess
# Win32_PerfFormattedData_Counters_PacketDirectQueueDepth
# Msft_WmiProvider_Counters
# Win32_PerfFormattedData_Counters_PacketDirectReceiveFilters
# Msft_WmiProvider_LoadOperationEvent
# Msft_WmiProvider_OperationEvent_Post
# MSFT_NetServiceStartFailedGroup
# Win32_PerfFormattedData_WindowsWorkflowFoundation4000_WFSystemWorkflow4000
# __InstanceCreationEvent
# CIM_SoftwareFeatureSoftwareElements
# Win32_SubDirectory
# Win32_ActiveRoute
# Win32_PerfRawData_TCPIPCounters_TCPIPPerformanceDiagnosticsPerCPU
# CIM_FileAction
# CIM_ClassIndication
# CIM_InfraredController
# Win32_ODBCDriverSpecification
# __TimerNextFiring
# MSFT_NetServiceLogonTypeNotGranted
# CIM_SoftwareFeatureSAPImplementation
# Win32_PerfRawData_LocalSessionManager_TerminalServices
# Win32_BootConfiguration
# Win32_PerfFormattedData_NETFramework_NETCLRLocksAndThreads
# Win32_ClientApplicationSetting
# CIM_ClassCreation
# Win32_PerfRawData_WorkflowServiceHost4000_WorkflowServiceHost4000
# __ClassDeletionEvent
# Win32_ActionCheck
# MSFT_NetServiceStopControlSuccess
# Win32_PhysicalMemoryLocation
# Win32_PerfRawData_NETFramework_NETCLRMemory
# Win32_PerfFormattedData_ServiceModel4000_ServiceModelService4000
# Win32_DefragAnalysis
# Msft_WmiProvider_ExecQueryAsyncEvent_Pre
# CIM_MonitorSetting
# Win32_PerfRawData_Counters_PacketDirectQueueDepth
# Win32_RoamingProfileBackgroundUploadParams
# Win32_PerfFormattedData_NETFramework_NETCLRInterop
# Win32_OperatingSystem
# Msft_Providers
# CIM_SoftwareElementChecks
# Win32_Condition
# Win32_PointingDevice
# Win32_PerfRawData_WinNatCounters_WinNATInstance
# Win32_PnPDeviceProperty
# Win32_PerfFormattedData_Lsa_SecurityPerProcessStatistics
# Win32_CodecFile
# Win32_PerfFormattedData_GPUPerformanceCounters_GPUProcessMemory
# Win32_PerfFormattedData_Counters_FileSystemDiskActivity
# Win32_PerfRawData_MicrosoftWindowsRemoteDesktopServicesRemoteFXSynth3dvsc_RemoteFXSynth3DVSCVMDevice
# Win32_PerfRawData_Counters_IPHTTPSSession
# CIM_Dependency
# CIM_CoolingDevice
# Win32_LogicalProgramGroupDirectory
# Win32_PerfRawData_PerfOS_System
# Win32_PerfFormattedData_NETFramework_NETCLRJit
# Win32_PerfFormattedData_Tcpip_UDPv6
# Win32_Process
# Win32_RegistryAction
# Win32_UserDesktop
# Win32_ReserveCost
# Win32_SoundDevice
# __EventGenerator
# Win32_FolderRedirection
# Win32_SystemUsers
# CIM_DeviceAccessedByFile
# OfficeSoftwareProtectionService
# OfficeSoftwareProtectionProduct
# CIM_ProductProductDependency
# Win32_NetworkConnection
# Msft_WmiProvider_DeleteClassAsyncEvent_Post
# Win32_PerfRawData_HvStats_HyperVHypervisor
# Win32_PerfRawData_NETFramework_NETCLRSecurity
# CIM_ServiceSAPDependency
# __InstanceOperationEvent
# CIM_RelatedStatistics
# __thisNAMESPACE
# MSFT_WmiSelfEvent
# Win32_LogicalShareAuditing
# Win32_OnBoardDevice
# Win32_PerfFormattedData_Counters_IPsecDriver
# Win32_ScheduledJob
# Win32_PerfFormattedData_Counters_SMBServerSessions
# Win32_PerfFormattedData_NETDataProviderforSqlServer_NETDataProviderforSqlServer
# __ObjectProviderRegistration
# MSFT_NetBadServiceState
# CIM_USBDevice
# CIM_Sensor
# Win32_PerfFormattedData_Counters_PacerFlow
# Win32_PerfRawData_PerfProc_Process
# Msft_WmiProvider_DeleteInstanceAsyncEvent_Pre
# CIM_InstIndication
# Win32_CurrentTime
# Win32_PerfRawData_Counters_Synchronization
# Win32_PerfFormattedData_Counters_WFPReauthentication
# CIM_DeviceErrorCounts
# Win32_VolumeUserQuota
# Win32_PnPDevicePropertyBoolean
# CIM_SettingCheck
# Win32_PerfFormattedData_SMSvcHost3000_SMSvcHost3000
# Win32_ComputerSystemProcessor
# Win32_DCOMApplicationSetting
# Win32_PerfFormattedData_Tcpip_IPv4
# Win32_PerfRawData_WnvCounters_NetworkVirtualization
# Win32_PageFileElementSetting
# CIM_MediaAccessDevice
# __ClassOperationEvent
# Win32_PerfRawData_NETFramework_NETCLRJit
# Win32_RoamingProfileSlowLinkParams
# Win32_ProductResource
# CIM_ExecuteProgram
# Win32_PerfRawData_Counters_PacerFlow
# Win32_TypeLibraryAction
# Win32_PerfRawData_Counters_PowerShellWorkflow
# Win32_PerfFormattedData_Spooler_PrintQueue
# Win32_COMApplicationSettings
# CIM_SoftwareElementVersionCheck
# CIM_PackageTempSensor
# Win32_BIOS
# Win32_PerfRawData_HvStats_HyperVHypervisorRootVirtualProcessor
# Win32_ServerSession
# Win32_TemperatureProbe
# CIM_UserDevice
# CIM_DiskDrive
# Win32_SystemAccount
# Win32_ODBCDriverSoftwareElement
# Win32_PerfFormattedData_Counters_IPsecAuthIPIPv4
# Win32_PerfRawData_ESENT_DatabaseTableClasses
# Win32_PerfFormattedData_PerfDisk_LogicalDisk
# Win32_PerfRawData_PerfOS_Cache
# Win32_PerfRawData_PerfProc_Thread
# Win32_PerfFormattedData_MicrosoftWindowsRemoteDesktopServicesRemoteFXSynth3dvsc_RemoteFXSynth3DVSCVMTransportChannel
# Win32_PerfFormattedData_Counters_IPHTTPSGlobal
# Win32_PerfRawData_Counters_XHCICommonBuffer
# Win32_PerfRawData_PerfOS_Objects
# Win32_DeviceBus
# Msft_WmiProvider_PutClassAsyncEvent_Post
# Win32_PerfRawData_WinNatCounters_WinNATUDP
# __NamespaceOperationEvent
# Win32_PerfFormattedData_MicrosoftWindowsRemoteDesktopServicesRemoteFXSynth3dvsc_RemoteFXSynth3DVSCVMDevice
# Win32_ModuleLoadTrace
# Win32_PerfRawData_Tcpip_IPv6
# Win32_PerfRawData_GPUPerformanceCounters_GPUNonLocalAdapterMemory
# Win32_LoadOrderGroupServiceMembers
# __AbsoluteTimerInstruction
# Win32_SystemSystemDriver
# CIM_Battery
# Win32_DiskQuota
# CIM_PhysicalConnector
# Win32_PerfRawData_Counters_IPsecIKEv2IPv6
# Win32_PerfFormattedData_OfflineFiles_OfflineFiles
# Win32_FolderRedirectionHealth
# CIM_ComputerSystemResource
# Win32_SystemProcesses
# MSFT_WmiEssEvent
# CIM_VideoControllerResolution
# Win32_PhysicalMemoryArray
# Win32_LogicalDiskRootDirectory
# Win32_PCMCIAController
# CIM_Docked
# Win32_PerfFormattedData_Counters_HyperVVirtualMachineBusPipes
# Win32_PerfRawData_ESENT_Database
# CIM_FileSystem
# CIM_DirectoryAction
# Win32_LoadOrderGroup
# Win32_PerfRawData_ServiceModel4000_ServiceModelService4000
# Msft_WmiProvider_InitializationOperationFailureEvent
# Win32_ComputerSystemProduct
# CIM_AssociatedSupplyVoltageSensor
# Win32_PerfRawData_Counters_PacketDirectReceiveCounters
# CIM_InstDeletion
# CIM_PhysicalPackage
# Win32_PerfFormattedData_GPUPerformanceCounters_GPUNonLocalAdapterMemory
# Win32_PerfFormattedData_PerfOS_Processor
# Win32_PerfRawData_Tcpip_TCPv4
# Win32_PerfRawData_NETCLRNetworking4000_NETCLRNetworking4000
# CIM_CDROMDrive
# MSFT_NetTransactTimeout
# CIM_CollectionOfMSEs
# Win32_PerfFormattedData_WorkflowServiceHost4000_WorkflowServiceHost4000
# Win32_PerfRawData_NETCLRData_NETCLRData
# CIM_DisketteDrive
# Win32_PrinterShare
# Win32_PerfFormattedData_Counters_HTTPServiceUrlGroups
# Win32_PerfFormattedData_Counters_Synchronization
# Win32_JobObjectStatus
# Win32_PnPDevicePropertySint32
# Win32_DesktopMonitor
# Win32_PerfFormattedData_Counters_WSManQuotaStatistics
# Win32_ProcessStartTrace
# Win32_PerfRawData_Counters_XHCIInterrupter
# Win32_PerfFormattedData_McePerfCtr_ClassificationEngineRulePackageCache
# CIM_FromDirectorySpecification
# Win32_PerfFormattedData_LocalSessionManager_TerminalServices
# CIM_ReplacementSet
# Win32_PerfFormattedData_NETFramework_NETCLRSecurity
# MSFT_NetRevertedToLastKnownGood
# Win32_PerfFormattedData_WinNatCounters_WinNATInstance
# MSFT_NetServiceExitFailedSpecific
# CIM_Keyboard
# CIM_PackageInChassis
# Win32_SerialPort
# Win32_PnPDevicePropertySint64
# Win32_PnPDevicePropertyString
# Win32_PerfFormattedData_MSDTCBridge4000_MSDTCBridge4000
# MSFT_NetSevereServiceFailed
# Win32_PortableBattery
# Win32_PerfFormattedData_RemoteAccess_RASPort
# Win32_IDEControllerDevice
# Win32_MemoryDeviceLocation
# CIM_UninterruptiblePowerSupply
# Win32_PerfFormattedData_Tcpip_UDPv4
# Win32_PerfFormattedData_ESENT_DatabaseTableClasses
# Win32_LoggedOnUser
# Win32_PerfRawData_PerfNet_Browser
# Win32_PerfRawData_WindowsWorkflowFoundation4000_WFSystemWorkflow4000
# CIM_BIOSLoadedInNV
# Win32_Group
# Win32_OfflineFilesSuspendInfo
# CIM_HostedJobDestination
# Win32_SystemDriverPNPEntity
# Win32_SecurityDescriptorHelper
# CIM_Service
# Win32_NamedJobObjectLimit
# Win32_DuplicateFileAction
# Win32_ProgramGroupContents
# Win32_ACE
# __ExtrinsicEvent
# Win32_PerfRawData_PerfProc_JobObjectDetails
# Win32_PerfFormattedData_TCPIPCounters_TCPIPPerformanceDiagnostics
# Win32_PerfFormattedData_MSDTC_DistributedTransactionCoordinator
# CIM_AggregatePSExtent
# Win32_PerfFormattedData_OfflineFiles_ClientSideCaching
# Win32_FolderRedirectionHealthConfiguration
# CIM_ComputerSystemDMA
# Win32_PerfRawData_Counters_PerProcessorNetworkInterfaceCardActivity
# CIM_SAPSAPDependency
# Win32_TokenGroups
# Win32_SystemDesktop
# Win32_PerfRawData_Counters_PacketDirectTransmitCounters
# CIM_ParallelController
# Win32_PerfFormattedData_Counters_SynchronizationNuma
# Msft_WmiProvider_NewQuery_Pre
# Win32_PerfFormattedData_Counters_WFPv6
# Win32_IP4PersistedRouteTable
# Win32_PerfRawData_Counters_StorageSpacesVirtualDisk
# Msft_WmiProvider_OperationEvent
# Win32_PerfFormattedData_PeerDistSvc_BranchCache
# Win32_OfflineFilesUserConfiguration
# Win32_PerfFormattedData_Counters_IPsecIKEv1IPv4
# CIM_UnitaryComputerSystem
# SoftwareLicensingTokenActivationLicense
# Win32_PerfFormattedData_Counters_StorageSpacesVirtualDisk
# CIM_SupportAccess
# Win32_PerfRawData_WindowsWorkflowFoundation3000_WindowsWorkflowFoundation
# Win32_FolderRedirectionUserConfiguration
# Msft_WmiProvider_CreateClassEnumAsyncEvent_Pre
# CIM_TemperatureSensor
# Win32_PerfRawData
# Win32_PerfFormattedData_Tcpip_TCPv6
# Win32_ProductSoftwareFeatures
# Win32_MSIResource
# CIM_System
# Win32_SystemSetting
# CIM_BootOSFromFS
# CIM_ComputerSystemPackage
# CIM_HeatPipe
# CIM_CopyFileAction
# Win32_VoltageProbe
# Msft_WmiProvider_ProvideEvents_Pre
# CIM_AssociatedSupplyCurrentSensor
# CIM_HostedBootService
# CIM_Thread
# Win32_UserInDomain
# Win32_PerfFormattedData_Counters_PowerShellWorkflow
# CIM_Slot
# Win32_PerfFormattedData_PerfProc_JobObject
# Win32_SystemBootConfiguration
# CIM_Refrigeration
# Win32_Account
# Win32_PerfRawData_Lsa_SecurityPerProcessStatistics
# Win32_PerfRawData_Counters_FileSystemDiskActivity
# Win32_PnPDevicePropertyDateTime
# Win32_PerfRawData_Counters_ThermalZoneInformation
# __NamespaceDeletionEvent
# Win32_NamedJobObjectSecLimitSetting
# Win32_UTCTime
# Win32_SecuritySettingOfLogicalFile
# Win32_RoamingUserHealthConfiguration
# CIM_CollectionSetting
# CIM_SystemComponent
# Win32_PerfRawData_Counters_PacerPipe
# __Trustee
# __EventQueueOverflowEvent
# MSFT_NetServiceRecoveryFailed
# Win32_ShortcutAction
# Win32_PerfFormattedData_WinNatCounters_WinNAT
# Win32_PerfRawData_MicrosoftWindowsRemoteDesktopServicesRemoteFXSynth3dvsc_RemoteFXSynth3DVSCVMTransportChannel
# Win32_PerfRawData_TapiSrv_Telephony
# CIM_Check
# Msft_WmiProvider_CancelQuery_Post
# Win32_MemoryArrayLocation
# CIM_DependencyContext
# Win32_DependentService
# CIM_StorageDefect
# Win32_NetworkAdapterConfiguration
# Win32_ApplicationCommandLine
# Win32_PerfRawData_NETFramework_NETCLRRemoting
# __ExtendedStatus
# Win32_PerfRawData_WindowsMediaPlayer_WindowsMediaPlayerMetadata
# CIM_VideoSetting
# Win32_SystemSlot
# Win32_BaseBoard
# Win32_PerfRawData_rdyboost_ReadyBoostCache
# Win32_PerfFormattedData_Tcpip_NBTConnection
# Win32_PerfRawData_Counters_IPsecIKEv1IPv6
# Win32_LogonSession
# Win32_VolumeQuota
# CIM_NonVolatileStorage
# Win32_PerfRawData_Spooler_PrintQueue
# Win32_OfflineFilesItem
# Win32_OfflineFilesHealth
# Msft_WmiProvider_DeleteClassAsyncEvent_Pre
# Win32_PnPDevicePropertyStringArray
# __Event
# Win32_PerfFormattedData_ESENT_Database
# Win32_PerfRawData_ESENT_DatabaseDatabases
# CIM_BasedOn
# Win32_PerfFormattedData_Counters_PacketDirectReceiveCounters
# Win32_OfflineFilesCache
# Win32_SystemProgramGroups
# Win32_PerfRawData_Counters_TeredoRelay
# CIM_DesktopMonitor
# CIM_Memory
# Win32_PortConnector
# CIM_ElementCapacity
# Win32_PerfFormattedData_WinNatCounters_WinNATTCP
# Win32_PerfFormattedData_WindowsMediaPlayer_WindowsMediaPlayerMetadata
# Win32_LogicalFileAuditing
# CIM_MonitorResolution
# Win32_LogicalProgramGroup
# __InstanceModificationEvent
# CIM_BootService
# CIM_ComputerSystemMappedIO
# CIM_RunningOS
# Win32_PerfFormattedData_Counters_PerProcessorNetworkActivityCycles
# CIM_ExtraCapacityGroup
# CIM_RemoveFileAction
# Win32_USBHub
# Win32_InfraredDevice
# MSFT_NCProvEvent
# CIM_OSVersionCheck
# Win32_PerfRawData_PerfNet_Redirector
# Win32_IniFileSpecification
# Win32_SystemTimeZone
# MSFT_WmiCancelNotificationSink
# Win32_PerfFormattedData_Counters_StorageSpacesTier
# Win32_PerfRawData_Counters_IPsecDriver
# Win32_PnPDevicePropertyUint16
# CIM_IRQ
# MSFT_NetServiceConfigBackoutFailed
# Win32_VolumeQuotaSetting
# Win32_PnPDevicePropertyUint8
# Win32_PerfRawData_DistributedRoutingTablePerf_DistributedRoutingTable
# Win32_PerfFormattedData_Counters_TeredoRelay
# Win32_PnPDevicePropertySint64Array
# Win32_OfflineFilesBackgroundSync
# Win32_NTLogEventUser
# CIM_VolumeSet
# CIM_BIOSFeatureBIOSElements
# CIM_LogicalIdentity
# Win32_PerfFormattedData_PowerMeterCounter_PowerMeter
# Win32_ExtensionInfoAction
# Win32_PnPDevicePropertySint8Array
# Win32_PnPDevicePropertyBinary
# Msft_WmiProvider_CreateClassEnumAsyncEvent_Post
# CIM_DMA
# Win32_PnPDevicePropertyReal32
# Win32_PerfFormattedData_PerfProc_JobObjectDetails
# Win32_UserProfile
# Win32_SystemMemoryResource
# Win32_PrivilegesStatus
# __EventConsumer
# Win32_Property
# Win32_PerfRawData_PeerDistSvc_BranchCache
# CIM_ComputerSystem
# __InstanceDeletionEvent
# Win32_PerfFormattedData_NETCLRNetworking4000_NETCLRNetworking4000
# Win32_SystemDevices
# Win32_PingStatus
# SoftwareLicensingProduct
# Win32_PerfFormattedData_ServiceModelService3000_ServiceModelService3000
# CIM_ProductParentChild
# Win32_PerfRawData_GPUPerformanceCounters_GPULocalAdapterMemory
# Win32_OSRecoveryConfiguration
# Win32_NetworkAdapter
# Win32_PerfFormattedData_Lsa_SecuritySystemWideStatistics
# Win32_SystemConfigurationChangeEvent
# CIM_LogicalDisk
# MSFT_NetServiceSlowStartup
# Win32_Bus
# Win32_InstalledSoftwareElement
# Win32_ClusterShare
# CIM_DeviceServiceImplementation
# Win32_NetworkLoginProfile
# Win32_AllocatedResource
# Win32_PerfRawData_NETDataProviderforOracle_NETDataProviderforOracle
# __FilterToConsumerBinding
# Win32_PNPAllocatedResource
# Win32_PerfFormattedData_Counters_XHCICommonBuffer
# __SecurityDescriptor
# Win32_PerfRawData_Counters_HyperVVirtualMachineBusProviderPipes
# __ClassCreationEvent
# Win32_ComponentCategory
# Win32_PerfFormattedData_Counters_IPsecAuthIPIPv6
# CIM_MemoryOnCard
# MSFT_NetServiceShutdownFailed
# Win32_PerfFormattedData_ESENT_DatabaseDatabases
# MSFT_NetServiceStartFailedII
# Win32_LUID
# CIM_ProtectedSpaceExtent
# Win32_PerfFormattedData_Counters_IPsecIKEv2IPv6
# Win32_PerfFormattedData_PerfOS_PagingFile
# Win32_GroupInDomain
# MSFT_WmiFilterDeactivated
# __Win32Provider
# Win32_SoftwareElement
# Win32_Service
# Win32_PerfFormattedData_ServiceModel4000_ServiceModelEndpoint4000
# CIM_ElementConfiguration
# Win32_WMIElementSetting
# Win32_PerfRawData_Counters_GenericIKEv1AuthIPandIKEv2
# Win32_Fan
# __Provider
# CIM_ModifySettingAction
# Win32_Keyboard
# Win32_SystemDriver
# Win32_Share
# Win32_ServiceSpecificationService
# CIM_FileStorage
# Win32_PerfRawData_Counters_AppVClientStreamedDataPercentage
# Win32_PerfRawData_NETCLRNetworking_NETCLRNetworking
# Win32_USBController
# MSFT_NetServiceNotInteractive
# CIM_SoftwareElement
# Win32_SoftwareFeatureSoftwareElements
# Win32_PerfRawData_Counters_IPsecAuthIPIPv6
# CIM_CreateDirectoryAction
# Win32_PerfRawData_GPUPerformanceCounters_GPUProcessMemory
# Win32_PerfFormattedData_Counters_EventTracingforWindowsSession
# Msft_WmiProvider_DeleteInstanceAsyncEvent_Post
# Win32_PerfRawData_Counters_PhysicalNetworkInterfaceCardActivity
# CIM_CardInSlot
# CIM_ElementSetting
# Win32_NetworkClient
# Win32_LUIDandAttributes
# Win32_Binary
# Win32_NTEventlogFile
# CIM_StorageError
# CIM_PSExtentBasedOnPExtent
# Win32_PerfRawData_Counters_WFPv4
# Win32_PerfFormattedData_PerfProc_Process
# Win32_DisplayConfiguration
# CIM_Export
# Win32_PowerManagementEvent
# Win32_IP4RouteTable
# Win32_ODBCAttribute
# Win32_PerfRawData_NETFramework_NETCLRExceptions
# CIM_PhysicalElementLocation
# Win32_PerfRawData_Tcpip_UDPv6
# Win32_AutochkSetting
# Win32_PerfRawData_ServiceModelOperation3000_ServiceModelOperation3000
# Win32_PerfRawData_PerfOS_NUMANodeMemory
# Win32_DfsNodeTarget
# Win32_PerfFormattedData_RemoteAccess_RASTotal
# CIM_LogicalElement
# Win32_ClassicCOMClassSetting
# Win32_PerfRawData_Lsa_SecuritySystemWideStatistics
# Win32_PerfFormattedData_AuthorizationManager_AuthorizationManagerApplications
# CIM_NetworkAdapter
# CIM_WORMDrive
# Win32_InstalledProgramFramework
# Msft_WmiProvider_LoadOperationFailureEvent
# Msft_WmiProvider_CreateInstanceEnumAsyncEvent_Post
# Msft_WmiProvider_AccessCheck_Pre
# MSFT_NCProvClientConnected
# CIM_Processor
# CIM_Container
# Win32_CommandLineAccess
# Win32_PerfRawData_RemoteAccess_RASTotal
# Win32_PerfRawData_ServiceModel4000_ServiceModelOperation4000
# Win32_Thread
# CIM_Job
# Win32_ProcessStopTrace
# Win32_LogicalDiskToPartition
# Win32_PerfRawData_Tcpip_ICMP
# CIM_CompatibleProduct
# CIM_AssociatedAlarm
# Win32_PerfRawData_Tcpip_TCPv6
# Win32_NamedJobObjectProcess
# Win32_TapeDrive
# Win32_PerfFormattedData_NETFramework_NETCLRExceptions
# Win32_OfflineFilesMachineConfiguration
# MSFT_NetServiceCrashNoAction
# Win32_PnPDevicePropertyUint64Array
# CIM_LogicalDevice
# Win32_PerfRawData_Counters_WFPClassify
# Win32_DiskDrive
# CIM_ProcessThread
# CIM_OperatingSystemSoftwareFeature
# Win32_PerfFormattedData_Counters_GenericIKEv1AuthIPandIKEv2
# Win32_PerfFormattedData_GPUPerformanceCounters_GPULocalAdapterMemory
# Win32_PerfFormattedData_MicrosoftWindowsW32TimePerf_WindowsTimeService
# Win32_PerfRawData_Tcpip_NetworkAdapter
# Win32_LogicalDisk
# Msft_WmiProvider_GetObjectAsyncEvent_Pre
# CIM_PackageCooling
# Win32_1394Controller
# Win32_PerfRawData_Counters_WFP
# Win32_PerfRawData_NETFramework_NETCLRLocksAndThreads
# Win32_PatchPackage
# CIM_MemoryCapacity
# CIM_RedundancyComponent
# Win32_PerfFormattedData_Counters_EventTracingforWindows
# Win32_PerfRawData_UGatherer_SearchGathererProjects
# MSFT_WMI_GenericNonCOMEvent
# CIM_RebootAction
# MSFT_NetFirstLogonFailedII
# CIM_JobDestination
# Win32_ComputerSystemEvent
# Win32_OfflineFilesAssociatedItems
# Msft_WmiProvider_ProvideEvents_Post
# CIM_RealizesPExtent
# MSFT_NetServiceControlSuccess
# Win32_ShadowVolumeSupport
# Win32_OptionalFeature
# CIM_BootServiceAccessBySAP
# Win32_PerfFormattedData_BITS_BITSNetUtilization
# CIM_InstalledOS
# Win32_COMApplication
# CIM_AlarmDevice
# Win32_PerfFormattedData_Counters_PerProcessorNetworkInterfaceCardActivity
# CIM_RemoteFileSystem
# Win32_NetworkAdapterSetting
# CIM_Mount
# Win32_PerfRawData_Counters_PerProcessorNetworkActivityCycles
# Win32_SoftwareElementResource
# Win32_SecuritySettingOwner
# Win32_LogicalShareAccess
# CIM_NFS
# Win32_PerfFormattedData_Counters_PacerPipe
# Win32_PerfRawData_PerfProc_JobObject
# Win32_SessionProcess
# Win32_Trustee
# Win32_ThreadStartTrace
# Win32_PerfFormattedData_Counters_RDMAActivity
# Win32_ComputerShutdownEvent
# Win32_LogicalFileGroup
# Win32_CurrentProbe
# Win32_SoftwareElementCheck
# Win32_PerfRawData_ServiceModel4000_ServiceModelEndpoint4000
# Win32_PerfFormattedData_Tcpip_ICMPv6
# MSFT_NetCallToFunctionFailedII
# Win32_OfflineFilesChangeInfo
# __NTLMUser9X
# MSFT_NetCallToFunctionFailed
# Win32_PerfRawData_Counters_SMBServer
# OfficeSoftwareProtectionTokenActivationLicense
# Win32_PerfRawData_PerfNet_ServerWorkQueues
# Win32_DfsTarget
# CIM_LocalFileSystem
# CIM_Fan
# Win32_QuickFixEngineering
# NTEventlogProviderConfig
# Win32_PrinterController
# Win32_PerfRawData_Counters_EventTracingforWindowsSession
# Msft_WmiProvider_ComServerLoadOperationEvent
# CIM_USBControllerHasHub
# Win32_PerfRawData_Counters_WFPv6
# Win32_PerfFormattedData_Counters_HyperVVirtualMachineBusProviderPipes
# Win32_PerfFormattedData_UGatherer_SearchGathererProjects
# RegistryValueChangeEvent
# Win32_AccountSID
# Win32_OfflineFilesDirtyInfo
# CIM_PhysicalLink
# CIM_DeviceConnection
# MSFT_NetServiceExitFailed
# Win32_Product
# Win32_NamedJobObject
# Win32_PerfFormattedData_NETMemoryCache40_NETMemoryCache40
# __NAMESPACE
# CIM_ManagementController
# Win32_PerfFormattedData_Tcpip_TCPv4
# CIM_Process
# Win32_PerfFormattedData
# Win32_UserStateConfigurationControls
# Win32_PerfRawData_NETFramework_NETCLRInterop
# Win32_ClassInfoAction
# CIM_PowerSupply
# Win32_LogicalFileOwner
# CIM_AssociatedCooling
# Win32_PerfRawData_OfflineFiles_ClientSideCaching
# Win32_PerfRawData_PerfOS_Memory
# Win32_PerfFormattedData_Counters_StorageSpacesWriteCache
# CIM_HostedService
# Win32_PortResource
# Win32_PerfFormattedData_Counters_PacketDirectTransmitCounters
# CIM_AssociatedProcessorMemory
# Win32_PerfRawData_Counters_TeredoClient
# Win32_PerfFormattedData_NETFramework_NETCLRRemoting
# Win32_PnPSignedDriverCIMDataFile
# MSFT_WmiRegisterNotificationSink
# __ClassProviderRegistration
# Win32_Session
# Win32_Environment
# CIM_VideoBIOSFeatureVideoBIOSElements
# Win32_TimeZone
# MSFT_NCProvAccessCheck
# MSFT_NetConnectionTimeout
# Win32_SMBIOSMemory
# Win32_RemoveIniAction
# CIM_SystemResource
# __IntervalTimerInstruction
# Win32_ODBCDataSourceSpecification
# CIM_SCSIController
# Win32_PerfFormattedData_McePerfCtr_ClassificationEngineContentAnalysisSession
# Win32_RemoveFileAction
# Win32_PerfRawData_Counters_SMBClientShares
# CIM_USBHub
# Win32_MemoryArray
# CIM_MemoryMappedIO
# Win32_DeviceMemoryAddress
# CIM_DiscreteSensor
# CIM_ServiceServiceDependency
# Win32_PerfFormattedData_Counters_XHCIInterrupter
# Win32_PerfFormattedData_HvStats_HyperVHypervisor
# Win32_LaunchCondition
# CIM_SettingContext
# Win32_PerfRawData_HvStats_HyperVHypervisorLogicalProcessor
# StdRegProv
# Win32_InstalledWin32Program
# Win32_PatchFile
# Win32_PerfFormattedData_Counters_TeredoClient
# CIM_InstalledSoftwareElement
# Win32_TCPIPPrinterPort
# Win32_PerfFormattedData_PerfDisk_PhysicalDisk
# MSFT_WmiThreadPoolThreadCreated
# __TimerInstruction
# Win32_PnPDevicePropertyDateTimeArray
# Win32_ProcessStartup
# Win32_IRQResource
# CIM_HostedFileSystem
# Win32_SystemEnclosure
# Win32_PerfFormattedData_ServiceModel4000_ServiceModelOperation4000
# Win32_ShortcutFile
# Win32_PerfFormattedData_PowerMeterCounter_EnergyMeter
# Win32_DirectorySpecification


